#!/usr/bin/env python
# -- coding: utf-8 --
import os

stopwords = '''את
            לא
            של
            אני
            על
            זה
            עם
            כל
            הוא
            אם
            או
            גם
            יותר
            יש
            לי
            מה
            אבל
            פורום
            אז
            טוב
            רק
            כי
            שלי
            היה
            בפורום
            אין
            עוד
            היא
            אחד
            ב
            ל
            עד
            לך
            כמו
            להיות
            אתה
            כמה
            אנחנו
            הם
            כבר
            אנשים
            אפשר
            תודה
            שלא
            אותו
            ה
            מאוד
            הרבה
            ולא
            ממש
            לו
            א
            מי
            חיים
            בית
            שאני
            יכול
            שהוא
            כך
            הזה
            איך
            היום
            קצת
            עכשיו
            שם
            בכל
            יהיה
            תמיד
            י
            שלך
            הכי
            ש
            בו
            לעשות
            צריך
            כן
            פעם
            לכם
            ואני
            משהו
            אל
            שלו
            שיש
            ו
            וגם
            אתכם
            אחרי
            בנושא
            כדי
            פשוט
            לפני
            שזה
            אותי
            אנו
            למה
            דבר
            כ
            כאן
            אולי
            טובים
            רוצה
            שנה
            בעלי
            החיים
            למען
            אתם
            מ
            בין
            יום
            זאת
            איזה
            ביותר
            לה
            אחת
            הכל
            הפורומים
            לכל
            אלא
            פה
            יודע
            שלום
            דקות
            לנו
            השנה
            דרך
            אדם
            נראה
            זו
            היחידה
            רוצים
            בכלל
            טובה
            שלנו
            האם
            הייתי
            הלב
            היו
            ח
            שדרות
            בלי
            להם
            שאתה
            אותה
            מקום
            ואתם
            חלק
            בן
            בואו
            אחר
            האחת
            אותך
            כמובן
            בגלל
            באמת
            מישהו
            ילדים
            אותם
            הפורום
            טיפוח
            וזה
            ר
            שהם
            אך
            מזמין
            ישראל
            כוס
            זמן
            ועוד
            הילדים
            עדיין
            כזה
            עושה
            שום
            לקחת
            העולם
            תפוז
            לראות
            לפורום
            וכל
            לקבל
            נכון
            יוצא
            לעולם
            גדול
            אפילו
            ניתן
            שני
            אוכל
            קשה
            משחק
            ביום
            ככה
            אמא
            בת
            השבוע
            נוספים
            לגבי
            בבית
            אחרת
            לפי
            ללא
            שנים
            הזמן
            שמן
            מעט
            לפחות
            אף
            שוב
            שלהם
            במקום
            כולם
            נועית
            הבא
            מעל
            לב
            המון
            לדבר
            ע
            אוהב
            מוסיפים
            חצי
            בעיקר
            כפות
            לפעמים
            שהיא
            הנהלת
            ועל
            ק
            אוהבים
            ת
            יודעת
            ד
            גרוע
            שאנחנו
            מים
            לילדים
            בארץ
            מודיע
            אשמח
            שלכם
            פחות
            לכולם
            די
            אהבה
            יכולה
            דברים
            הקהילה
            לעזור
            פרטים
            בדיוק
            מלח
            קל
            הראשי
            שלה
            להוסיף
            השני
            לדעתי
            בר
            למרות
            שגם
            מוזמנים
            לאחר
            במה
            חושב
            מאד
            יפה
            להגשים
            חדש
            קטן
            מחפשים
            שמח
            מדברים
            ואם
            במיוחד
            עבודה
            מדי
            ואז
            חשוב
            שאם
            אוהבת
            פעמים
            מנהלת
            אומר
            מול
            קשר
            מנהל
            שיהיה
            שאין
            שאנו
            האהבה
            ס
            הצטרפו
            כפית
            בשביל
            החגים
            אופן
            לתת
            כף
            בתוך
            סוכר
            גיל
            בהצלחה
            והוא
            מקווה
            סתם
            ויש
            נגד
            כמעט
            שאת
            עולה
            אי
            מספר
            ראשון
            לדרך
            נהיה
            לעצב
            עושים
            ולנהל
            היתה
            עליו
            מזה
            הייתה
            בא
            בפרס
            חלות
            ראש
            מזמינים
            טיפים
            מכבי
            רבה
            הורים
            ‡
            מקרה
            קרן
            המוצלח
            להגיע
            גדולה
            כנראה
            החמשיר
            הראשון
            פלפל
            המשחק
            וכאן
            לדעת
            ואת
            גרועים
            ספר
            אגב
            אחרים
            להגיד
            בתפוז
            והעולם
            אופנה
            דווקא
            מספיק
            שעות
            תמונות
            כשאנחנו
            שוקולד
            ולכן
            ג
            לקרוא
            לניהול
            שבוע
            ויופי
            חלום
            בה
            שהיה
            שאלה
            מקומה
            הזו
            בפורומים
            החדש
            מתאמצים
            שחקן
            שמזינים
            נשמת
            בערך
            מכל
            ומה
            רגל
            כסף
            רואה
            קטנה
            בצל
            בעולם
            אינטרנט
            חוץ
            ברור
            הולך
            חושבת
            לזה
            כלום
            הן
            כאלה
            בטוח
            הדבר
            תהיה
            מגיע
            סוף
            האמת
            ממנו
            מיכל
            החדשה
            לתרום
            האנשים
            ועד
            בדרך
            אצלי
            ההורים
            בני
            מתוך
            כאשר
            לבד
            ראיתי
            מצב
            מלא
            לבחור
            נשמח
            החג
            רע
            עוף
            מן
            להביא
            מצאתי
            כתובות
            מעניין
            צריכה
            להכנס
            לחלוטין
            שעה
            מתכון
            קודם
            תשובות
            מדובר
            ניהול
            מזל
            כדאי
            יהיו
            ההודעות
            בוקר
            נילוות
            איפה
            בעיה
            קמח
            ללכת
            פורומים
            אמר
            נושא
            ההכנה
            בבקשה
            שכל
            הזאת
            למשחק
            פנינה
            תחרות
            חבר
            לקנות
            מהם
            רגע
            גרם
            אלו
            עצמו
            מראש
            הכלב
            כולנו
            עדיף
            איתו
            למשל
            לבשל
            למי
            רעיונות
            הבלוג
            רוב
            אביב
            כרגע
            בסוף
            אלה
            לחג
            ערוץ
            שווה
            באופן
            מאמין
            לבן
            בזה
            הכבוד
            לראש
            ם
            ימי
            שחור
            בצורה
            בעמוד
            ועם
            וחצי
            האלה
            תמונה
            ך
            בשלב
            משחקים
            כש
            \"
            i
            me
            my
            myself
            we
            our
            ours
            ourselves
            you
            your
            yours
            yourself
            yourselves
            he
            him
            his
            himself
            she
            her
            hers
            herself
            it
            its
            itself
            they
            them
            their
            theirs
            themselves
            what
            which
            who
            whom
            this
            that
            these
            those
            am
            is
            are
            was
            were
            be
            been
            being
            have
            has
            had
            having
            do
            does
            did
            doing
            a
            an
            the
            and
            but
            if
            or
            because
            as
            until
            while
            of
            at
            by
            for
            with
            about
            against
            between
            into
            through
            during
            before
            after
            above
            below
            to
            from
            up
            down
            in
            out
            on
            off
            over
            under
            again
            further
            then
            once
            here
            there
            when
            where
            why
            how
            all
            any
            both
            each
            few
            more
            most
            other
            some
            such
            no
            nor
            not
            only
            own
            same
            so
            than
            too
            very
            s
            t
            can
            will
            just
            don
            should
            now
נו'''

stopwords = stopwords.split("\n")


def remove_stop_words(directory):
    for filename in os.listdir(directory):
        try:
            sub_directory = unicode(directory + u'\\{}'.format(filename))
            for sub_filename in os.listdir(sub_directory):
                with open(sub_directory + '\\new_' + sub_filename, 'w') as out:
                    with open(sub_directory + '\\' + sub_filename) as inp:
                        for line in inp:
                            b = 1
                            for word in stopwords:
                                if word == line.replace("\n", ''):
                                    b = 0
                            if b == 1:
                                out.write(line)
                os.remove(sub_directory + '\\' + sub_filename)
        except:
            pass
